/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.*;

import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author PC
 */
public class MainUI extends javax.swing.JFrame {

    private ArrayList<Song> songs;

    public MainUI() {
        songs = new ArrayList<>();
        loadFile();
        initComponents();
        setLocationRelativeTo(null);
        fillTable(songs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        title = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        myFaButton = new javax.swing.JButton();
        instrumentmusicBotton = new javax.swing.JButton();
        lyricBotton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();
        homeTab = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        songList = new javax.swing.JTable();
        songSearch = new javax.swing.JPanel();
        songSearchButton = new javax.swing.JButton();
        songField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        songPlayB = new javax.swing.JButton();
        addSongB = new javax.swing.JButton();
        deleteSongB = new javax.swing.JButton();
        favTab = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        favtable = new javax.swing.JTable();
        songSearch1 = new javax.swing.JPanel();
        songSearchButton1 = new javax.swing.JButton();
        songField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        songPlayB1 = new javax.swing.JButton();
        addSongB1 = new javax.swing.JButton();
        deleteSongB1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.selectedForeground"));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("My Music");
        title.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        getContentPane().add(title, gridBagConstraints);

        menu.setLayout(new java.awt.GridBagLayout());

        homeButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        homeButton.setText("Home");
        homeButton.setPreferredSize(new java.awt.Dimension(150, 50));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(9, 16, 0, 14);
        menu.add(homeButton, gridBagConstraints);

        myFaButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        myFaButton.setText("My Favorite");
        myFaButton.setPreferredSize(new java.awt.Dimension(150, 50));
        myFaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myFaButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(9, 16, 0, 14);
        menu.add(myFaButton, gridBagConstraints);

        instrumentmusicBotton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        instrumentmusicBotton.setText("Instrument Music");
        instrumentmusicBotton.setPreferredSize(new java.awt.Dimension(150, 50));
        instrumentmusicBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instrumentmusicBottonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(9, 16, 0, 14);
        menu.add(instrumentmusicBotton, gridBagConstraints);

        lyricBotton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lyricBotton.setText("lyric Music");
        lyricBotton.setPreferredSize(new java.awt.Dimension(150, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(9, 16, 0, 14);
        menu.add(lyricBotton, gridBagConstraints);

        aboutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aboutButton.setText("About");
        aboutButton.setPreferredSize(new java.awt.Dimension(150, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(9, 16, 0, 14);
        menu.add(aboutButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(menu, gridBagConstraints);

        homeTab.setLayout(new java.awt.GridBagLayout());

        songList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title", "Author", "Genre", "Year"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        songList.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(songList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        homeTab.add(jScrollPane2, gridBagConstraints);

        songSearch.setLayout(new java.awt.GridBagLayout());

        songSearchButton.setText("Search");
        songSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                songSearchButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        songSearch.add(songSearchButton, gridBagConstraints);

        songField.setPreferredSize(new java.awt.Dimension(250, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 15);
        songSearch.add(songField, gridBagConstraints);

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        songSearch.add(jButton1, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        homeTab.add(songSearch, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        songPlayB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        songPlayB.setText("Play");
        songPlayB.setToolTipText("");
        songPlayB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                songPlayBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 20, 10);
        jPanel1.add(songPlayB, gridBagConstraints);

        addSongB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addSongB.setText("Add Song");
        addSongB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSongBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 20, 10);
        jPanel1.add(addSongB, gridBagConstraints);

        deleteSongB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteSongB.setText("Delete ");
        deleteSongB.setToolTipText("");
        deleteSongB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSongBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 20, 10);
        jPanel1.add(deleteSongB, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        homeTab.add(jPanel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 5;
        getContentPane().add(homeTab, gridBagConstraints);

        favTab.setLayout(new java.awt.GridBagLayout());

        favtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title", "Author", "Genre", "Year"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        favtable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(favtable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        favTab.add(jScrollPane3, gridBagConstraints);

        songSearch1.setLayout(new java.awt.GridBagLayout());

        songSearchButton1.setText("Search");
        songSearchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                songSearchButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        songSearch1.add(songSearchButton1, gridBagConstraints);

        songField1.setPreferredSize(new java.awt.Dimension(250, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 15);
        songSearch1.add(songField1, gridBagConstraints);

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        songSearch1.add(jButton2, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        favTab.add(songSearch1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        songPlayB1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        songPlayB1.setText("Play");
        songPlayB1.setToolTipText("");
        songPlayB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                songPlayB1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 20, 10);
        jPanel2.add(songPlayB1, gridBagConstraints);

        addSongB1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addSongB1.setText("Add Song");
        addSongB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSongB1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 20, 10);
        jPanel2.add(addSongB1, gridBagConstraints);

        deleteSongB1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteSongB1.setText("Delete ");
        deleteSongB1.setToolTipText("");
        deleteSongB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSongB1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 20, 10);
        jPanel2.add(deleteSongB1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        favTab.add(jPanel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 5;
        getContentPane().add(favTab, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeButtonActionPerformed

    private void myFaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myFaButtonActionPerformed
        
    }//GEN-LAST:event_myFaButtonActionPerformed

    private void songSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songSearchButtonActionPerformed
        String searchtext = songField.getText();
        fillTable(searchSong(searchtext));


    }//GEN-LAST:event_songSearchButtonActionPerformed

    private void addSongBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSongBActionPerformed
        new add(songs).setVisible(true);
    }//GEN-LAST:event_addSongBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fillTable(songs);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void songPlayBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songPlayBActionPerformed
        if (songList.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Please select a song to play", "Message", 1);
        } else {
            Song song = songs.get(songList.getSelectedRow());
            MusicPlayerFrame player = new MusicPlayerFrame(song);
            player.setVisible(true);
            player.setLocationRelativeTo(this);

        }
    }//GEN-LAST:event_songPlayBActionPerformed

    private void deleteSongBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSongBActionPerformed
      
        if (songList.getSelectedRow() != -1) {
            int option = JOptionPane.showConfirmDialog(this, "Do you want to delete the song: " + songs.get(songList.getSelectedRow()).getTitle(), "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (option == JOptionPane.YES_OPTION) {
                songs.remove(songList.getSelectedRow());

            }
        }
        fillTable(songs);
        saveToFile();  
    }//GEN-LAST:event_deleteSongBActionPerformed

    private void songSearchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songSearchButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_songSearchButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void songPlayB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songPlayB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_songPlayB1ActionPerformed

    private void addSongB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSongB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addSongB1ActionPerformed

    private void deleteSongB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSongB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteSongB1ActionPerformed

    private void instrumentmusicBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instrumentmusicBottonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instrumentmusicBottonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutButton;
    private javax.swing.JButton addSongB;
    private javax.swing.JButton addSongB1;
    private javax.swing.JButton deleteSongB;
    private javax.swing.JButton deleteSongB1;
    private javax.swing.JPanel favTab;
    private javax.swing.JTable favtable;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel homeTab;
    private javax.swing.JButton instrumentmusicBotton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton lyricBotton;
    private javax.swing.JPanel menu;
    private javax.swing.JButton myFaButton;
    private javax.swing.JTextField songField;
    private javax.swing.JTextField songField1;
    private javax.swing.JTable songList;
    private javax.swing.JButton songPlayB;
    private javax.swing.JButton songPlayB1;
    private javax.swing.JPanel songSearch;
    private javax.swing.JPanel songSearch1;
    private javax.swing.JButton songSearchButton;
    private javax.swing.JButton songSearchButton1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    private void loadFile() {
        String fileName = "List.data";
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream(fileName))) {
            this.songs = (ArrayList<Song>) ois.readObject();
            ois.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error load file: " + ex.getMessage(), "Message", 1);
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error load file: " + ex.getMessage(), "Message", 1);
        }
    }

    private void saveToFile() {
        String fileName = "List.data";
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(fileName))) {
            oos.writeObject(songs);
            oos.close();

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error save file: " + ex.getMessage(), "Message", 1);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error save file: " + ex.getMessage(), "Message", 1);

        }
    }

    private void fillTable(ArrayList<Song> list) {
        DefaultTableModel model = (DefaultTableModel) songList.getModel();
        int rowCount = songList.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        for (Song song : list) {
            Object[] row = new Object[]{song.getTitle(), song.getAuthor(), song.getGenre(), song.getYear()};
            model.addRow(row);
        }
    }
private void fillfavTable(ArrayList<Song> list) {
        DefaultTableModel model = (DefaultTableModel) favtable.getModel();
        int rowCount = favtable.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        for (Song song : list) {
            Object[] row = new Object[]{song.getTitle(), song.getAuthor(), song.getGenre(), song.getYear()};
            model.addRow(row);
        }
    }
    private ArrayList<Song> searchSong(String searchtext) {
        ArrayList<Song> result = new ArrayList<>();
        for (Song song : songs) {
            if (song.getTitle().contains(searchtext)) {
                result.add(song);
            } else if (song.getAuthor().contains(searchtext)) {
                result.add(song);
            } else if (song.getGenre().contains(searchtext)) {
                result.add(song);
            } else if (Integer.toString(song.getYear()).contains(searchtext)) {
                result.add(song);
            }

        }

        return result;

    }

}
